### ISSUE TITLE
AcrylicWindowXEffect和AeroWindowXEffect在win7上不支持

### ISSUE THREAD

**Issue by dzx815** [Panuon/Panuon.UI.Silver#34]
AcrylicWindowXEffect在win7的实际效果
![image](https://user-images.githubusercontent.com/15151459/139524942-61ab3cf9-48a6-4c74-9a65-723d1b686f69.png)

AeroWindowXEffect在win7的实际效果
![image](https://user-images.githubusercontent.com/15151459/139524974-8d88f80f-26dd-4367-a7fe-485274ee5f84.png)

如果不打算在win7支持，建议增加对系统的判断来处理此效果，比如win7及更低版本系统不生效，方便兼容多个系统版本。

**Comment by Mochengvia** [comment]
感谢你的反馈。
由于系统更新问题，即使是Windows的小版本更新也有可能会导致样式失效或显示异常。例如，AcrylicWindowEffect在Windows10 1909以上的版本中会出现严重的性能问题。
由于不知道这些BUG会在何时修复，因此PanuonUI不会在代码中添加对此问题的处理，这会给项目带来不必要的维护成本。
若要解决此问题，你应当在逻辑代码中对系统版本进行判断，并根据系统版本创建相应的WindowXEffect。WindowXEffect可以在csharp代码中动态创建并应用。

**Comment by dzx815** [comment]
好的
