### ISSUE TITLE
NoticeBox问题，在Page里面开一个线程Show，会直接卡死

### ISSUE THREAD

**Issue by dzx815** [Panuon/Panuon.UI.Silver#38]
`   public partial class Page1 : Page
    {
        public Page1()
        {
            InitializeComponent();
            Thread tt = new Thread(tttt);
             tt.Start();
        }
        private void tttt()
       {
           NoticeBox.Show("NoticeBox style configuration is placed in App.xaml. ", "Tips");//这里会卡死
        }
  }
`

**Comment by Mochengvia** [comment]
感谢你的反馈。
此问题已在v2.2.13.2版本修复。
如果仍然出现问题，请重新打开此反馈。

**Comment by dzx815** [comment]
这个问题，在v2.2.13.3依然存在，你那边可以试一下

**Comment by dzx815** [comment]
不要在其他的代码里使用NoticeBox.Show，

就单单这部分代码有NoticeBox.Show，这个问题就能复现。

**Comment by Mochengvia** [comment]
此问题将在下一个版本中修复。
暂时可以在首次调用时通过使用Application.Current.Dispatcher.Invoke来解决此BUG。

**Comment by Mochengvia** [comment]
此问题已在v2.2.4版本中修复。
如果仍有问题，请在此留言
