### ISSUE TITLE
PendingBox在win7系统无法正常运行，用的示例代码直接运行就报错，有截图

### ISSUE THREAD

**Issue by dzx815** [Panuon/Panuon.UI.Silver#43]
![image](https://user-images.githubusercontent.com/15151459/143795400-565aeb01-7daf-446d-b019-3de3edc65667.png)

![image](https://user-images.githubusercontent.com/15151459/143795446-2f895e72-0b71-4d6c-8714-82c81e819e87.png)

**Comment by dzx815** [comment]
这里有说明，有系统版本限制
Minimum supported client | Windows 10, version 1607 [desktop apps only]

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow

**Comment by Mochengvia** [comment]
好的，收到

**Comment by dzx815** [comment]
还有一个问题，如果我设置一定时间后关闭，然后在代码内关闭前又手动点击按钮关闭PendingBox ，如下代码

`var handler = PendingBox.Show(this, "PendingBox style configuration is placed in App.xaml.", "Caption", true);
            //handler.Cancelling += ...
            Thread.Sleep(3000);
            handler.Close();`

然后会报此错误，这个如果能PendingBoxWindow里面做判断，代码用起来会更省事一些。

![image](https://user-images.githubusercontent.com/15151459/143798648-fc5b551a-9a31-4907-8a25-b20c021d163f.png)

**Comment by Mochengvia** [comment]
好的，已收到

**Comment by Mochengvia** [comment]
此问题已在新版本中修复
