### ISSUE TITLE
datagrid header有一部分留白

### ISSUE THREAD

**Issue by lishuangquan1987** [Panuon/Panuon.UI.Silver#58]
现象：
![image](https://user-images.githubusercontent.com/15365329/167244628-db997241-c1d3-4808-a4a2-9caac4649120.png)
解决办法：
需要修改一下如下代码：
![image](https://user-images.githubusercontent.com/15365329/167244661-5b01f082-8dae-4698-8384-3592e00b34c5.png)

**Comment by Mochengvia** [comment]
感谢反馈。
此处留白是为了遵循WPF原生样式的设定；如果不希望留白，可以将DataGridHelper.IsVerticalScrollBarCrossingColumnHeaderPanel属性设置为True。


------------------ 原始邮件 ------------------
发件人: lishuangquan1987 ***@***.***&gt;
发送时间: 2022年5月7日 15:51
收件人: Panuon/Panuon.UI.Silver ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Panuon/Panuon.UI.Silver] datagrid header有一部分留白 (Issue #58)





 
现象：
 
 解决办法：
 需要修改一下如下代码：

**Comment by lishuangquan1987** [comment]
> 感谢反馈。 此处留白是为了遵循WPF原生样式的设定；如果不希望留白，可以将DataGridHelper.IsVerticalScrollBarCrossingColumnHeaderPanel属性设置为True。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lishuangquan1987 ***@***.***&gt; 发送时间: 2022年5月7日 15:51 收件人: Panuon/Panuon.UI.Silver ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [Panuon/Panuon.UI.Silver] datagrid header有一部分留白 (Issue #58) 现象： 解决办法： 需要修改一下如下代码： — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我加了 DataGridHelper.IsVerticalScrollBarCrossingColumnHeaderPanel属性设置为True，还是有空白：
![image](https://user-images.githubusercontent.com/15365329/167321625-202352ac-cac7-4d5d-aec1-a1e198947485.png)

**Comment by Mochengvia** [comment]
我检查了代码，发现IsVerticalScrollBarCrossingColumnHeaderPanel属性与IsHorizontalScrollBarCrossingFrozenColumns的效果写反。
这个错误修复已经完成，将在下一个版本(2.2.19)中一起发布。
