### ISSUE TITLE
在2.0里面怎么实现messagebox啊~ 

### ISSUE THREAD

**Issue by DJhentai** [Panuon/Panuon.UI.Silver#6]
看到代码里面好像没有哦==

**Comment by Panuon** [comment]
2.2里暂未提供MessageBox，将于这两周内的下一个版本提供



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DJhentai ***@***.***&gt;
发送时间: 2021年6月4日 09:38
收件人: PanuonOrg/Panuon.UI.Silver ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[PanuonOrg/Panuon.UI.Silver] 在2.0里面怎么实现messagebox啊~  (#6)

**Comment by DJhentai** [comment]
Tks! 多谢大佬回复~

**Comment by Mochengvia** [comment]
MessageBoxX已在2.2.9版本中提供
