### ISSUE TITLE
会有新的UIBrowser么

### ISSUE THREAD

**Issue by DamianRice** [Panuon/Panuon.UI.Silver#61]
麻烦问一下V2.X版本的会有更新的UIBrowser么

**Comment by Mochengvia** [comment]
抱歉，没有相关的计划。
UIBrowser在重新设计后，将作为更强大的前端开发协作软件(商业产品)，在未来两个月内发布。


------------------ 原始邮件 ------------------
发件人: DamianRice ***@***.***&gt;
发送时间: 2022年6月19日 00:03
收件人: Panuon/Panuon.UI.Silver ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Panuon/Panuon.UI.Silver] 会有新的UIBrowser么 (Issue #61)





 
麻烦问一下V2.X版本的会有更新的UIBrowser么

**Comment by DamianRice** [comment]
> 

那后续有没有针对个人开发者的文档相关完善计划，因为现在雀语上的中文文档有些东西找不到。我大致参照UIBrowser的接口看了一下，Native部分的接口应该基本都是通用的？

十分感谢您回复！

**Comment by Mochengvia** [comment]
2.2的文档以github页面中的wiki为准
语雀上的文档已经不再更新了


------------------ 原始邮件 ------------------
发件人: DamianRice ***@***.***&gt;
发送时间: 2022年6月19日 07:54
收件人: Panuon/Panuon.UI.Silver ***@***.***&gt;
抄送: 末城via ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Panuon/Panuon.UI.Silver] 会有新的UIBrowser么 (Issue #61)





   
那后续有没有针对个人开发者的文档相关完善计划，因为现在雀语上的中文文档有些东西找不到。我大致参照UIBrowser的接口看了一下，Native部分的接口应该基本都是通用的？
 
十分感谢您回复！

**Comment by DamianRice** [comment]
万分感谢！
